spring.application.name=Ecommerce

# Database Configuration - Neon Tech Cloud PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-spring-feather-ac95314b-pooler.sa-east-1.aws.neon.tech/ecommerce_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ju1tmjHM3BVo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwtSecret=QWERTYUIOPASDFGHJKLZXCVBNMQWERTYUIOPASDFGHJKLZXCVBNMQWERTYUIOPASDFGHJKLZXCVBNM
# 1 day in milliseconds
app.jwtExpirationMs=86400000

# Server Configuration
server.port=8080

# Spring Session Configuration
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=3600
